#! /bin/csh -f
source ../.setPDK.csh

set topcell = croc_chip
set defpath = ../openroad/out/croc.def
set outfile = ./out/croc.gds

mkdir -p ./out

if ( -e ${outfile} ) then
    echo "Removing existing file: ${outfile}"
    rm -f ${outfile}
endif

klayout -zz -rd design_name=${topcell} \
        -rd in_def=${defpath} \
        -rd in_files=" ../technology/gds/sg13cmos5l_stdcell.gds \
                       ../technology/gds/ez130_8t.gds \
                       ../technology/gds/sg13cmos5l_io.gds \
                       ../technology/gds/bondpad5l_70x70.gds \
                       ../technology/gds/RM_IHPSG13_1P_512x32_c2_bm_bist.gds" \
        -rd out_file=${outfile} \
        -rd tech_file=./.klayout/tech/${technology}.lyt \
        -rd layer_map='' \
        -rd seal_file='' \
        -rd config_file='' \
        -rd lef_files='' \
        -rd allow_empty='RM_IHPSG13_(1P|2P)_BITKIT_16x2_(CORNER|EDGE_TB|LE_con_corner|LE_con_edge_lr|LE_con_tap_lr|POWER_ramtap|TAP|TAP_LR)$' \
        -rm .klayout/def2stream.py
